// Shared page shell for the Diorama documentation site (docs-site/).
// Every emitter (scripts/docs-site/build.mjs, scripts/docs-gallery/generate.mjs,
// scripts/docs-site/floorplans.mjs) routes its HTML through sitePage() and its
// stylesheet through writeSharedAssets() so the whole published site carries one
// topbar, one theme, and one CSS file. No runtime deps.

import fs from 'node:fs';
import path from 'node:path';

export function htmlEsc(s) {
  return String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

export const GEN_HEADER = (tool) =>
  `<!-- GENERATED by ${tool} — DO NOT EDIT BY HAND. -->\n`;

// Site-wide sections shown in the sticky topbar. `href` is relative to the
// site root; sitePage() prefixes it by depth.
export const SITE_SECTIONS = [
  { key: 'home', label: 'Home', href: 'index.html' },
  { key: 'guide', label: 'Guide', href: 'guide/getting-started.html' },
  { key: 'models', label: 'Models', href: 'models/index.html' },
  { key: 'floorplans', label: 'Floor plans', href: 'floorplans/index.html' },
  // The live demo page is the full app (staged by scripts/docs-site/demo.mjs),
  // not a sitePage() emit, so it never carries section==='demo' and simply
  // never highlights — the relative href + ?demo query resolve fine at any depth.
  { key: 'demo', label: 'Live demo', href: 'demo/index.html?demo=ranch-3bed' },
];

/**
 * Full page wrapper.
 * @param {object} o
 * @param {string} o.title      document title (suffixed with "— Diorama")
 * @param {string} o.section    active SITE_SECTIONS key
 * @param {number} o.depth      directory depth below the site root (0 = root)
 * @param {string} o.main       inner HTML of <main>
 * @param {string} [o.sidebar]  optional sidebar HTML (nav links); omitted = full-width
 * @param {string} [o.version]  app version for the topbar meta
 * @param {string} [o.date]     build date for the topbar meta
 */
export function sitePage({ title, section, depth, main, sidebar, version, date }) {
  const prefix = '../'.repeat(depth);
  const nav = SITE_SECTIONS.map((s) =>
    `<a class="topnav-link${s.key === section ? ' active' : ''}" href="${prefix}${s.href}">${htmlEsc(s.label)}</a>`).join('');
  const meta = version ? `<span class="brand-meta">v${htmlEsc(version)}${date ? ' · ' + htmlEsc(date) : ''}</span>` : '';
  const menuBtn = sidebar
    ? `<button class="menu-btn" aria-label="Toggle navigation" onclick="document.body.classList.toggle('nav-open')">☰</button>` : '';
  const layout = sidebar
    ? `<div class="layout"><aside class="sidebar">${sidebar}</aside><main class="main">${main}</main></div>`
    : `<div class="layout"><main class="main main-solo">${main}</main></div>`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${htmlEsc(title)} — Diorama</title>
<link rel="stylesheet" href="${prefix}assets/site.css">
</head>
<body>
<header class="topbar">
${menuBtn}<a class="brand" href="${prefix}index.html">Diorama</a>
<nav class="topnav">${nav}</nav>
${meta}
</header>
${layout}
<script>
document.querySelectorAll('.nav-link').forEach(function(a){a.addEventListener('click',function(){document.body.classList.remove('nav-open');});});
</script>
</body>
</html>`;
}

// ── minimal markdown → HTML (guide pages) ─────────────────────────────────────
// Supports: # headings, paragraphs, - / 1. lists (one nesting level), ```
// fences, | tables, > quotes, **bold**, *italic*, `code`, [text](href),
// ![alt](src), --- rules. Enough for authored guide prose; not a general parser.
export function mdToHtml(md) {
  const lines = String(md).replace(/\r\n/g, '\n').split('\n');
  let out = '';
  let i = 0;
  // GitHub-style heading slugs (per-document unique) so in-page anchors work.
  const usedSlugs = new Map();
  const slugOf = (raw) => {
    const base = raw
      .replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1')   // links/images → text
      .replace(/[`*_]/g, '')                        // inline markers
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-') || 'section';
    const n = usedSlugs.get(base) || 0;
    usedSlugs.set(base, n + 1);
    return n === 0 ? base : `${base}-${n + 1}`;
  };
  const inline = (s) => htmlEsc(s)
    .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img loading="lazy" src="$2" alt="$1">')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/(^|[\s(])\*([^*\s][^*]*)\*/g, '$1<em>$2</em>');
  while (i < lines.length) {
    const ln = lines[i];
    if (/^\s*$/.test(ln)) { i++; continue; }
    if (/^```/.test(ln)) {
      const buf = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i])) buf.push(lines[i++]);
      i++;
      out += `<pre><code>${htmlEsc(buf.join('\n'))}</code></pre>\n`;
      continue;
    }
    const h = ln.match(/^(#{1,4})\s+(.*)$/);
    if (h) {
      const lvl = h[1].length;
      const id = slugOf(h[2]);
      out += `<h${lvl} id="${id}">${inline(h[2])}<a class="hlink" href="#${id}" aria-label="Link to this section">#</a></h${lvl}>\n`;
      i++; continue;
    }
    if (/^---+\s*$/.test(ln)) { out += '<hr>\n'; i++; continue; }
    if (/^\|/.test(ln)) {
      const rows = [];
      while (i < lines.length && /^\|/.test(lines[i])) rows.push(lines[i++]);
      const cells = (r) => r.replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
      let t = '<div class="table-wrap"><table><thead><tr>'
        + cells(rows[0]).map((c) => `<th>${inline(c)}</th>`).join('') + '</tr></thead><tbody>';
      for (const r of rows.slice(2)) t += '<tr>' + cells(r).map((c) => `<td>${inline(c)}</td>`).join('') + '</tr>';
      out += t + '</tbody></table></div>\n';
      continue;
    }
    if (/^>\s?/.test(ln)) {
      const buf = [];
      while (i < lines.length && /^>\s?/.test(lines[i])) buf.push(lines[i++].replace(/^>\s?/, ''));
      out += `<blockquote><p>${buf.map(inline).join('<br>')}</p></blockquote>\n`;
      continue;
    }
    const listM = ln.match(/^(\s*)([-*]|\d+\.)\s+/);
    if (listM) {
      const ordered = /\d/.test(listM[2]);
      const tag = ordered ? 'ol' : 'ul';
      let t = `<${tag}>`;
      while (i < lines.length) {
        const m = lines[i].match(/^(\s*)([-*]|\d+\.)\s+(.*)$/);
        if (!m) break;
        let item = m[3];
        i++;
        // nested one level
        let sub = '';
        while (i < lines.length) {
          const n = lines[i].match(/^\s{2,}([-*]|\d+\.)\s+(.*)$/);
          if (!n) break;
          sub += `<li>${inline(n[2])}</li>`;
          i++;
        }
        t += `<li>${inline(item)}${sub ? `<ul>${sub}</ul>` : ''}</li>`;
      }
      out += t + `</${tag}>\n`;
      continue;
    }
    // paragraph — consume until blank/structural line
    const buf = [ln];
    i++;
    while (i < lines.length && !/^\s*$/.test(lines[i]) && !/^(#{1,4}\s|```|\||>|---|\s*([-*]|\d+\.)\s)/.test(lines[i])) buf.push(lines[i++]);
    out += `<p>${buf.map(inline).join(' ')}</p>\n`;
  }
  return out;
}

// ── shared stylesheet ─────────────────────────────────────────────────────────
// Superset of the model-gallery theme (dark editor vibe) + site topnav, guide
// prose, and floorplan screenshot styles. One file at <root>/assets/site.css.
export const SITE_CSS = `/* GENERATED by scripts/docs-site/shell.mjs — DO NOT EDIT BY HAND. */
:root {
  --bg: #0f1115; --panel: #171a1f; --panel-2: #1c2027; --border: #262b33;
  --text: #e6e8eb; --muted: #9aa3ad; --accent: #4da3ff; --accent-dim: #2b3a4d;
  --code-bg: #10141a; --code-fg: #8fd0ff;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg); color: var(--text);
  font: 15px/1.5 system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
}
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }

.topbar {
  position: sticky; top: 0; z-index: 20; display: flex; align-items: center; gap: 14px;
  padding: 10px 18px; background: rgba(15,17,21,.92); backdrop-filter: blur(6px);
  border-bottom: 1px solid var(--border);
}
.brand { font-weight: 700; color: var(--text); font-size: 16px; }
.brand:hover { color: var(--accent); text-decoration: none; }
.brand-meta { color: var(--muted); font-size: 12.5px; margin-left: auto; }
.topnav { display: flex; gap: 4px; flex-wrap: wrap; }
.topnav-link {
  padding: 5px 12px; border-radius: 8px; color: var(--muted); font-size: 14px;
}
.topnav-link:hover { color: var(--text); background: var(--panel); text-decoration: none; }
.topnav-link.active { color: #fff; background: var(--accent-dim); }
.menu-btn {
  display: none; background: var(--panel-2); color: var(--text); border: 1px solid var(--border);
  border-radius: 8px; font-size: 17px; line-height: 1; padding: 6px 10px; cursor: pointer;
}

.layout { display: flex; align-items: flex-start; }
.sidebar {
  position: sticky; top: 49px; align-self: flex-start; flex: 0 0 250px; width: 250px;
  height: calc(100vh - 49px); overflow-y: auto; padding: 16px 10px 40px;
  border-right: 1px solid var(--border); background: var(--bg);
}
.nav { display: flex; flex-direction: column; gap: 2px; }
.nav-link {
  display: block; padding: 7px 12px; border-radius: 8px; color: var(--text);
  font-size: 14px; border-left: 3px solid transparent;
}
.nav-link:hover { background: var(--panel); text-decoration: none; }
.nav-link.active { background: var(--accent-dim); border-left-color: var(--accent); color: #fff; }
.nav-group-head { font-weight: 600; margin-top: 8px; }
.nav-sub { display: flex; flex-direction: column; gap: 2px; margin: 2px 0 4px 10px;
  padding-left: 6px; border-left: 1px solid var(--border); }
.nav-sub .nav-link { font-size: 13px; padding: 5px 10px; color: var(--muted); }
.nav-sub .nav-link:hover { color: var(--text); }
.nav-sub .nav-link.active { color: #fff; }

.main { flex: 1 1 auto; min-width: 0; padding: 24px 28px 80px; max-width: 1400px; }
.main-solo { max-width: 1100px; margin: 0 auto; }
.page-head h1 { margin: 0 0 6px; font-size: 26px; }
.page-head .intro { margin: 0 0 8px; color: var(--muted); max-width: 70ch; }
.group { margin-top: 30px; }
.group h2 {
  font-size: 18px; margin: 0 0 14px; padding-bottom: 6px; border-bottom: 1px solid var(--border);
}
.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); }
.card {
  background: var(--panel); border: 1px solid var(--border); border-radius: 12px; overflow: hidden;
  display: flex; flex-direction: column; scroll-margin-top: 64px;
}
.card:target { border-color: var(--accent); box-shadow: 0 0 0 2px var(--accent-dim); }
.card-img { display: block; background: #0b0d10; }
.card-img img { display: block; width: 100%; aspect-ratio: 1 / 1; object-fit: contain; }
.card-body { padding: 10px 12px 12px; display: flex; flex-direction: column; gap: 5px; }
.card-label { font-weight: 600; font-size: 14px; }
.card-id { align-self: flex-start; background: var(--code-bg); color: var(--code-fg);
  border: 1px solid var(--border); border-radius: 6px; padding: 1px 7px; font-size: 12px; }
.card-notes { color: var(--muted); font-size: 12.5px; }

.index-grid { display: grid; gap: 14px; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); }
.tile {
  display: flex; flex-direction: column; gap: 6px; padding: 16px 18px; background: var(--panel);
  border: 1px solid var(--border); border-radius: 12px; color: var(--text);
}
.tile:hover { border-color: var(--accent); text-decoration: none; }
.tile-title { font-weight: 600; font-size: 15px; }
.tile-count { color: var(--muted); font-size: 13px; }

/* guide prose */
.prose { max-width: 78ch; }
.prose h1 { font-size: 26px; margin: 0 0 10px; }
.prose h2 { font-size: 20px; margin: 34px 0 10px; padding-bottom: 6px; border-bottom: 1px solid var(--border); }
.prose .hlink { margin-left: 8px; color: var(--muted); text-decoration: none; opacity: 0;
  font-weight: 400; transition: opacity 0.12s; }
.prose h1:hover .hlink, .prose h2:hover .hlink, .prose h3:hover .hlink,
.prose h4:hover .hlink, .prose :target .hlink { opacity: 0.8; }
.prose h1, .prose h2, .prose h3, .prose h4 { scroll-margin-top: 70px; }
.prose h3 { font-size: 16px; margin: 24px 0 8px; }
.prose p, .prose li { color: var(--text); }
.prose li { margin: 3px 0; }
.prose code { background: var(--code-bg); color: var(--code-fg); border: 1px solid var(--border);
  border-radius: 5px; padding: 1px 5px; font-size: 13px; }
.prose pre { background: var(--code-bg); border: 1px solid var(--border); border-radius: 10px;
  padding: 12px 14px; overflow-x: auto; }
.prose pre code { background: none; border: none; padding: 0; }
.prose blockquote { margin: 12px 0; padding: 8px 14px; border-left: 3px solid var(--accent);
  background: var(--panel); border-radius: 0 8px 8px 0; color: var(--muted); }
.prose img { max-width: 100%; border: 1px solid var(--border); border-radius: 10px; }
.prose hr { border: none; border-top: 1px solid var(--border); margin: 26px 0; }
.table-wrap { overflow-x: auto; margin: 12px 0; }
.prose table, .table-wrap table { border-collapse: collapse; font-size: 14px; min-width: 50%; }
.prose th, .prose td, .table-wrap th, .table-wrap td {
  border: 1px solid var(--border); padding: 6px 10px; text-align: left; }
.prose th, .table-wrap th { background: var(--panel-2); }

/* floorplan pages */
.plan-grid { display: grid; gap: 18px; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); }
.plan-tile { display: flex; flex-direction: column; background: var(--panel);
  border: 1px solid var(--border); border-radius: 12px; overflow: hidden; color: var(--text); }
.plan-tile:hover { border-color: var(--accent); text-decoration: none; }
.plan-tile img { display: block; width: 100%; aspect-ratio: 4 / 3; object-fit: cover; background: #0b0d10; }
.plan-tile-body { padding: 12px 14px 14px; display: flex; flex-direction: column; gap: 4px; }
.plan-tile-title { font-weight: 600; font-size: 15px; }
.plan-tile-meta { color: var(--muted); font-size: 13px; }
.shot { margin: 0 0 18px; }
.shot img { display: block; width: 100%; max-width: 1280px; border: 1px solid var(--border);
  border-radius: 10px; background: #0b0d10; }
.shot figcaption { color: var(--muted); font-size: 13px; margin-top: 6px; }
.shot-grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); }
.dl-btn { display: inline-block; margin: 8px 0 4px; padding: 8px 16px; border-radius: 8px;
  background: var(--accent-dim); border: 1px solid var(--accent); color: #fff; font-weight: 600; }
.dl-btn:hover { background: var(--accent); text-decoration: none; }
/* "Open / view in live demo" deep-link — green accent, distinct from download. */
.demo-btn { display: inline-block; margin: 8px 8px 4px 0; padding: 8px 16px; border-radius: 8px;
  background: #17331f; border: 1px solid #2ec16a; color: #eafff2; font-weight: 600; }
.demo-btn:hover { background: #2ec16a; color: #04150b; text-decoration: none; }
.card-demo { align-self: flex-start; margin: 2px 0 0; padding: 4px 11px; font-size: 12.5px; }
.plan-notes { white-space: pre-wrap; background: var(--panel); border: 1px solid var(--border);
  border-radius: 10px; padding: 14px 16px; color: var(--text); max-width: 88ch; }

/* home hero */
.hero { padding: 40px 0 10px; }
.hero h1 { font-size: 34px; margin: 0 0 10px; }
.hero .tag { color: var(--muted); font-size: 17px; max-width: 62ch; }
.cta-row { display: flex; gap: 10px; flex-wrap: wrap; margin: 18px 0 6px; }
.feature-grid { display: grid; gap: 14px; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); margin-top: 24px; }

@media (max-width: 860px) {
  .menu-btn { display: inline-block; }
  .sidebar {
    position: fixed; top: 49px; left: 0; z-index: 15; height: calc(100vh - 49px);
    transform: translateX(-100%); transition: transform .18s ease; box-shadow: 2px 0 18px rgba(0,0,0,.5);
  }
  body.nav-open .sidebar { transform: translateX(0); }
  .main { padding: 20px 16px 64px; }
  .brand-meta { display: none; }
}
`;

// Write the shared stylesheet into <siteRoot>/assets/. Every emitter calls this
// so running any single script still yields a styled site.
export function writeSharedAssets(siteRoot) {
  fs.mkdirSync(path.join(siteRoot, 'assets'), { recursive: true });
  fs.writeFileSync(path.join(siteRoot, 'assets', 'site.css'), SITE_CSS);
}
