// Floorplan library build. Imports every plan module in plans/*.mjs, runs
// build() → a Store, wraps it in the standard export envelope
// { diorama: 2, name, exportedAt, store }, writes docs/floorplans/<id>.json
// (2-space pretty), validates each, and regenerates docs/floorplans/README.md
// (index table). Exits nonzero on any validation failure.
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { join, dirname } from 'node:path';
import { loadGeom } from './geom.mjs';
import { setGeom } from './lib.mjs';
import { validatePlan } from './validate.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const PLANS_DIR = join(HERE, 'plans');
const OUT_DIR = join(REPO, 'docs', 'floorplans');

// Fixed per-run timestamp (stable within a build; committed JSONs stay
// byte-identical across a no-op rebuild unless a plan actually changes).
const EXPORTED_AT = new Date().toISOString().slice(0, 10) + 'T00:00:00.000Z';

function footprintOf(store) {
  // Largest floor rect, formatted like "6600 × 6350 mm".
  let w = 0, d = 0;
  for (const f of store.floors) { if (f.w * f.d > w * d) { w = f.w; d = f.d; } }
  return `${w} × ${d} mm`;
}

function summaryLine(store) {
  // First line of notes = the "~451 sq ft · 1 floor · N rooms" summary.
  const first = (store.notes || '').split('\n')[0].trim();
  return first;
}

async function main() {
  const geom = await loadGeom();
  setGeom(geom);
  mkdirSync(OUT_DIR, { recursive: true });

  const files = readdirSync(PLANS_DIR).filter(f => f.endsWith('.mjs')).sort();
  if (!files.length) { console.error('No plan modules in plans/'); process.exit(1); }

  const rows = [];
  let totalChecks = 0, passedChecks = 0, failedPlans = 0;

  for (const file of files) {
    const mod = await import(pathToFileURL(join(PLANS_DIR, file)).href);
    const { id, name } = mod;
    if (!id || !name || typeof mod.build !== 'function') {
      console.error(`✗ ${file}: must export { id, name, build() }`);
      failedPlans++; continue;
    }
    let store;
    try { store = mod.build(); }
    catch (e) { console.error(`✗ ${id}: build() threw — ${e.stack || e}`); failedPlans++; continue; }

    const env = { diorama: 2, name, exportedAt: EXPORTED_AT, store };
    const outPath = join(OUT_DIR, `${id}.json`);
    writeFileSync(outPath, JSON.stringify(env, null, 2) + '\n');

    const { pass, checks } = validatePlan(env, geom);
    totalChecks += checks.length;
    passedChecks += checks.filter(c => c.ok).length;
    if (!pass) {
      failedPlans++;
      console.error(`✗ ${id} — ${checks.filter(c => !c.ok).length} FAILED:`);
      for (const c of checks) if (!c.ok) console.error(`    FAIL  ${c.msg}`);
    } else {
      console.log(`✓ ${id} — ${checks.length}/${checks.length} checks · ${store.floors.length} floor(s)`);
    }

    rows.push({
      id, name,
      floors: store.floors.length,
      footprint: footprintOf(store),
      summary: summaryLine(store),
    });
  }

  // Regenerate the index README.
  const lines = [
    '# Diorama floorplan library',
    '',
    'Importable demo floorplan configurations, generated by',
    '`npm run floorplans:build` from `scripts/floorplans/plans/*.mjs`. Each',
    '`<id>.json` is a standard Diorama export envelope — import it via',
    'Settings ▸ Data ▸ Configurations ▸ Import.',
    '',
    '| Plan | Floors | Footprint | Summary |',
    '|---|---|---|---|',
    ...rows.map(r => `| [${r.name}](${r.id}.json) | ${r.floors} | ${r.footprint} | ${r.summary} |`),
    '',
    `_${rows.length} plan(s). Regenerate with \`npm run floorplans:build\`._`,
    '',
  ];
  writeFileSync(join(OUT_DIR, 'README.md'), lines.join('\n'));

  console.log('');
  if (failedPlans > 0) {
    console.error(`FLOORPLANS FAIL — ${failedPlans} plan(s) failed · ${passedChecks}/${totalChecks} checks passed`);
    process.exit(1);
  }
  console.log(`FLOORPLANS PASS ${passedChecks}/${totalChecks} checks · ${rows.length} plan(s)`);
}

main().catch(e => { console.error(e.stack || e); process.exit(1); });
